---
- name: Ensure Home Assistant config directory exists
  ansible.builtin.file:
    path: "/home/{{ ansible_user_name }}/app/homeassistant_config"
    state: directory
    owner: "{{ ansible_user_name }}"
    group: "{{ ansible_user_name }}"
    mode: '0755'